Supports str hash_id in is_valid() as in __init__()
Before:
>>> croniter.is_valid('H 0 * * *', hash_id='abc')
Traceback (most recent call last):
...
TypeError: a bytes-like object is required, not 'str'

After:
>>> croniter.is_valid('H 0 * * *', hash_id='abc')
True